INSERT INTO ADDRESS(STREET, STATE, CITY, COUNTRY, ZIP) VALUES ('Calle Alcalá 31', 'Madrid', 'Madrid', 'Spain', '28901');
INSERT INTO ADDRESS(STREET, STATE, CITY, COUNTRY, ZIP) VALUES ('Down Street 50', 'Extremadura', 'Badajoz', 'Spain', '31845');
INSERT INTO ADDRESS(STREET, STATE, CITY, COUNTRY, ZIP) VALUES ('Calle Mayor 45', 'Castilla y León', 'Salamanca', 'Spain', '37871');

INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Juan', 'Juan@gmail.com', '2000-10-30', 1);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Pepe', 'Pepe@gmail.com', '1990-12-31', 2);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Postman', 'Postman@gmail.com', '1953-01-06', 1);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Guillever', 'Guillever@gmail.com', '1967-09-15', 2);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Lara', 'Lara@gmail.com', '1986-04-12', 1);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Sara', 'Sara@gmail.com', '1999-11-01', 3);
INSERT INTO USERS(NAME, EMAIL, BIRTHDATE, FK_ADDRESS) VALUES ('Leni', 'Leni1922@gmail.com', '1930-02-02', 1);